prd:
  catalog_name: mlops_prd
  schema_name: satisfaction_customer
acc:
  catalog_name: mlops_acc
  schema_name: satisfaction_customer
dev:
  catalog_name: mlops_dev
  schema_name: satisfaction_customer

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

features:
  - id
  - Gender
  - Customer Type
  - Age
  - Type of Travel
  - Class
  - Flight Distance
  - Inflight wifi service
  - Departure/Arrival time convenient
  - Ease of Online booking
  - Gate location
  - Food and drink
  - Online boarding
  - Seat comfort
  - Inflight entertainment
  - On-board service
  - Leg room service
  - Baggage handling
  - Checkin service
  - Inflight service
  - Cleanliness
  - Departure Delay in Minutes
  - Arrival Delay in Minutes

target: satisfaction_v2
