prd:
  catalog_name: mlops_prd
  schema_name: njavierb
acc:
  catalog_name: mlops_acc
  schema_name: njavierb
dev:
  catalog_name: mlops_dev
  schema_name: njavierb

experiment_name_basic: /Shared/satisfaction-customer-basic
experiment_name_custom: /Shared/satisfaction-customer-custom

parameters:
  solver: liblinear
  class_weight: balanced
  penalty: l1
  max_iter: 200
  C: 0.01

features:
  - id
  - Gender
  - Customer Type
  - Age
  - Type of Travel
  - Class
  - Flight Distance
  - Inflight wifi service
  - Departure/Arrival time convenient
  - Ease of Online booking
  - Gate location
  - Food and drink
  - Online boarding
  - Seat comfort
  - Inflight entertainment
  - On-board service
  - Leg room service
  - Baggage handling
  - Checkin service
  - Inflight service
  - Cleanliness
  - Departure Delay in Minutes
  - Arrival Delay in Minutes

target: satisfaction_v2
